#version 430

layout(local_size_x=16,local_size_y=16,local_size_z=1) in;

layout(r32f, binding=0) uniform image2D destTex;
layout(std430, binding=1) buffer WarpingPointStruct
{
	vec2 WarpingPoints[65536];
};

void main()
{
	ivec2 regionBase = ivec2(gl_WorkGroupID.x * 16, gl_WorkGroupID.y * 16);
	ivec2 localPos = ivec2(WarpingPoints[gl_LocalInvocationIndex]*16);
	ivec2 globalPos = regionBase + localPos;
	imageStore(destTex, globalPos, vec4(1.0,0.0,0.0,1.0));
}