#version 430

layout(local_size_x=16,local_size_y=16) in;
layout(std430, binding=0) buffer SamplePointStruct
{
	vec2 SamplePoints[256];
};
layout(std430, binding=1) buffer WarpingPointStruct
{
	vec2 WarpingPoints[65536];
};

void main()
{
	//copy uniform sample to warping points
	for (int i = 0; i < 256; i++)
	{
		for (int j = 0; j < 256; j++)
		{
			WarpingPoints[i*256+j] = SamplePoints[j];
		}
	}
}